/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartcityhomescreen;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author ASUS
 */
public class Homescreen extends javax.swing.JFrame {

    /**
     * Creates new form Home screen
     */
    public Homescreen() {
        initComponents();
        formap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentholder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addsensor = new javax.swing.JButton();
        removesensor = new javax.swing.JButton();
        viewsensor = new javax.swing.JButton();
        selectedpanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        stname = new javax.swing.JLabel();
        actsensors = new javax.swing.JLabel();
        lat = new javax.swing.JLabel();
        longi = new javax.swing.JLabel();
        mapholder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        componentholder.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));

        addsensor.setBackground(new java.awt.Color(153, 153, 153));
        addsensor.setText("Add Sensor Station");
        addsensor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addsensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsensorActionPerformed(evt);
            }
        });

        removesensor.setBackground(new java.awt.Color(255, 255, 255));
        removesensor.setText("Remove Sensor Station");
        removesensor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removesensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removesensorActionPerformed(evt);
            }
        });

        viewsensor.setBackground(new java.awt.Color(255, 255, 255));
        viewsensor.setText("View Sensor Station");
        viewsensor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewsensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsensorActionPerformed(evt);
            }
        });

        selectedpanel.setBackground(new java.awt.Color(248, 248, 248));
        selectedpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        heading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        heading.setText("Selected Sensor Station");

        stname.setText("Station Name :");

        actsensors.setText("No. of active sensors :");

        lat.setText("Latitude :");

        longi.setText("Longitude :");

        javax.swing.GroupLayout selectedpanelLayout = new javax.swing.GroupLayout(selectedpanel);
        selectedpanel.setLayout(selectedpanelLayout);
        selectedpanelLayout.setHorizontalGroup(
            selectedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedpanelLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(heading)
                .addGap(82, 82, 82))
            .addComponent(jSeparator1)
            .addGroup(selectedpanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(selectedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(longi)
                    .addComponent(lat)
                    .addComponent(actsensors)
                    .addComponent(stname))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectedpanelLayout.setVerticalGroup(
            selectedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedpanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(heading)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(stname)
                .addGap(35, 35, 35)
                .addComponent(actsensors)
                .addGap(44, 44, 44)
                .addComponent(lat)
                .addGap(31, 31, 31)
                .addComponent(longi)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        mapholder.setBackground(new java.awt.Color(204, 204, 204));
        mapholder.setToolTipText("MapContainer");

        javax.swing.GroupLayout componentholderLayout = new javax.swing.GroupLayout(componentholder);
        componentholder.setLayout(componentholderLayout);
        componentholderLayout.setHorizontalGroup(
            componentholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentholderLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(viewsensor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(addsensor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(removesensor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(componentholderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(selectedpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mapholder, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        componentholderLayout.setVerticalGroup(
            componentholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentholderLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(componentholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewsensor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addsensor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removesensor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(componentholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentholderLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(componentholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectedpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mapholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(componentholderLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(componentholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(componentholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addsensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addsensorActionPerformed

    private void removesensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removesensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removesensorActionPerformed

    private void viewsensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewsensorActionPerformed
    public void formap(){
        
        /*Lets test the map*/

         try {
            String imageUrl = "https://maps.googleapis.com/maps/api/staticmap?center=6.9612955,80.2440817&zoom=7&size=730x454&key=ABQIAAAAgb5KEVTm54vkPcAkU9xOvBR30EG5jFWfUzfYJTWEkWk2p04CHxTGDNV791-cU95kOnweeZ0SsURYSA&format=jpg";
            String destinationFile = "image.jpg";
            URL url = new URL(imageUrl);
            InputStream is = url.openStream();
            OutputStream os = new FileOutputStream(destinationFile);

            byte[] b = new byte[2048];
            int length;

            while ((length = is.read(b)) != -1) {
                os.write(b, 0, length);
            }

            is.close();
            os.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }
        
        ImageIcon iconicmap = new ImageIcon("image.jpg");
        
        mapholder.setIcon(iconicmap);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homescreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actsensors;
    private javax.swing.JButton addsensor;
    private javax.swing.JPanel componentholder;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lat;
    private javax.swing.JLabel longi;
    private javax.swing.JLabel mapholder;
    private javax.swing.JButton removesensor;
    private javax.swing.JPanel selectedpanel;
    private javax.swing.JLabel stname;
    private javax.swing.JButton viewsensor;
    // End of variables declaration//GEN-END:variables
}
